#!/bin/sh

INSMOD="/sbin/insmod"
MODPROBE="/sbin/modprobe"

im()
{
	modname=$1
	modsane=${1//-/_}
	params=$(eval echo \$OPT_${modsane})
	shift
	file=/lib/modules/${KVER}/${modname}.ko
	# the CS modules are in /lib/modules/$KVER/*,
	# own built modules are in /lib/modules/$KVER/kernel/... subdirectories
	if test -e $file; then
		echo "[$0]....... $INSMOD $file ${params:-$@}" 
		$INSMOD $file ${params:-$@}
		IM=$INSMOD
	else
		echo "[$0]...... $MODPROBE $modname $@"
		$MODPROBE $modname -v $@
		IM=$MODPROBE
	fi
}

case $1 in
start)
	read dummy dummy KVER dummy < /proc/version
	# make sure that modules.dep exists
	test -e /lib/modules/${KVER}/modules.dep || depmod -a
	NEWKERNEL=true
	test $KVER = 2.6.26.8-nevis && NEWKERNEL=false
	# set all "option foo ..." as OPT_foo="..." variables
	eval $(sed -n "/^options\s/{
		s/^options\s\(\S\+\)\s\(.*\)\$/OPT_\1=\"\2\"/;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		p }" /etc/modprobe.conf)
	im cs_frontpanel
	if test -e /bin/dt; then
		/bin/dt -ls01
		/bin/dt -ls02
		/bin/dt -c
		/bin/dt -t"init system..."
	fi
	im cnxt_kal
	im cnxt_base init=$($NEWKERNEL && echo 1 || echo 0)
	im cnxt_fb cnxtfb_standalone=1 cnxtfb_width=1280 cnxtfb_height=720
	im cnxt_lnx
	im cnxt_alsa
	im cs_control hdd_power=1
	im cnxt_i2c
	im cnxt_sata_drv

	im cifs
	im usbserial
	im ftdi_sio

	im stv6110 verbose=0
	im stv090x verbose=0
	im tda10023
	im avl2108
	im max2112
	im cs_frontend_prop
	im dvb-core
	/etc/init.d/load-fe-device $IM cs_frontend
	#im cs_frontend
	im md4

	;;
esac



